name: Deploy Lambda Layer
on:
  push:
    paths:
      - 'requirements.txt'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies to the layer directory
      run: |
        python -m pip install --upgrade pip
        mkdir -p layer/python/lib/python3.10/site-packages
        pip install -r requirements.txt -t layer/python/lib/python3.10/site-packages
    
    - name: Create a .zip file
      working-directory: layer
      run: zip -r ../layer.zip ./*
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
      
    - name: Publish layer
      run: |
        aws lambda publish-layer-version \
          --layer-name my-dependencies \
          --description "Python dependencies for Lambda" \
          --zip-file fileb://layer.zip \
          --compatible-runtimes python3.10
