name: Deploy Lambda Function
on:
  push:
    paths-ignore:
      - 'requirements.txt'
      - '.github/workflows/deploy_lambda_layer.yml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy source files to the directory
      run: |
        mkdir ./function
        cp ./src/* ./function
    
    - name: Create a .zip file
      working-directory: function
      run: zip -r ../function.zip ./*
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
      
    - name: Deploy on lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ vars.AWS_LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://function.zip
