name: Deploy Lambda Layer
on:
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/deploy_lambda_layer.yml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies to the layer directory
      run: |
        python -m pip install --upgrade pip
        mkdir -p layer/python/lib/python3.10/site-packages
        pip install -r requirements.txt -t layer/python/lib/python3.10/site-packages
    
    - name: Create a .zip file
      working-directory: layer
      run: zip -r ../layer.zip ./*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Upload to S3
      run: |
        aws s3 cp layer.zip s3://aws-lambda-discord-langchain/layers/layer.zip

    - name: Update Lambda layer
      run: |
        LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name aws-lambda-discord-langchain-dependencies \
          --description 'aws-lambda-discord-langchain-dependencies:$(git rev-parse --short "$GITHUB_SHA")' \
          --content S3Bucket=aws-lambda-discord-langchain,S3Key=layers/layer.zip \
          --compatible-runtimes python3.10 \
          --query 'Version' \
          --output text)
        aws lambda update-function-configuration \
          --function-name aws-lambda-discord-langchain \
          --layers "arn:aws:lambda:ap-northeast-1:437563817343:layer:aws-lambda-discord-langchain-dependencies:${LAYER_VERSION}"
