name: Deploy Lambda
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies to the directory
      run: |
        python -m pip install --upgrade pip
        mkdir ./deploy
        pip install -r requirements.txt --target ./deploy

    - name: Copy source files to the directory
      run: |
        cp ./src/* ./deploy
    
    - name: Create a .zip file
      working-directory: ./deploy
      run: zip -r ../function.zip ./*
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
      
    - name: Deploy on lambda
      run: |
        aws lambda update-function-code \
          --function-name YOUR_FUNCTION_NAME \
          --zip-file fileb://function.zip
